const words = [
  "Equality, Liberty, and Justice for All.",
  "Empowerment through freedom of choice.",
  "In the truest sense, freedom cannot be bestowed; it must be achieved.",
  "True freedom is thought to be in the realm of ideas rather than in the reality of action.",
  "Man is born free, and everywhere he is in chains. One man thinks himself the master of others, but remains more of a slave than they are.",
  "Freedom is the will to be responsible to ourselves.",
  "Freedom for the wolves has often meant death to the sheep.",
  "The end of law is not to abolish or restrain, but to preserve and enlarge freedom. For in all the states of created beings capable of laws, where there is no law, there is no freedom.",
  "Freedom is not worth having if it does not include the freedom to make mistakes.",
  "The only freedom which deserves the name, is that of pursuing our own good in our own way, so long as we do not attempt to deprive others of theirs, or impede their efforts to obtain it.",
  "Freedom is never voluntarily given by the oppressor; it must be demanded by the oppressed.",
  "I had reasoned this out in my mind, there was one of two things I had a right to, liberty or death; if I could not have one, I would have the other.",
  "You can't separate peace from freedom because no one can be at peace unless he has his freedom.",
  "The tree of liberty must be refreshed from time to time with the blood of patriots and tyrants. It is its natural manure.",
  "Without community, there is no liberation.",
  "If liberty means anything at all, it means the right to tell people what they do not want to hear.",
  "For to be free is not merely to cast off one's chains, but to live in a way that respects and enhances the freedom of others.",
  "Freedom would become the environment of an organism which is no longer concerned with its self-preservation but with its self-realization.",
  "I wish that every human life might be pure transparent freedom.",
  "Building a fairer, more inclusive society.",
  "Live for the moment.",
  "Those who would give up essential Liberty, to purchase a little temporary Safety, deserve neither Liberty nor Safety."
];
